# Generated by Django 2.1.7 on 2025-07-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SymptomsApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
